### ISSUE TITLE
xbrlChildren example URL returns no results

### ISSUE THREAD

**Issue by smoussa** [xbrlus/data_analysis_toolkit#2]
The URL example in the xbrlChildren REST API doc (after supplying an API key) returns a count of 0. Not sure where the error is.

Also, where does one find the GroupURI?

**Comment by bergant** [comment]
I am using this approach:

**1** Call Task=**xbrlCIKLookup** with `Ticker=ibm` to get company CIK:

           cik ticker                                 name  sic
    0000051143    ibm INTERNATIONAL BUSINESS MACHINES CORP 3570

**2** Call TASK=**xbrlNetwork** with 

    Element=ProfitLoss 
    Linkbase=Calculation
    CIK=0000051143
  
You will get all the fillings with xbrlus database internal **accessionID** and filing dates:

    accessionID filingDate                                                        extendedLinkRole
         135173 2015-07-28        http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFEARNINGS
         135173 2015-07-28       http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFCASHFLOWS
         135173 2015-07-28 http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFCHANGESINEQUITY
         142517 2015-10-27        http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFEARNINGS
         142517 2015-10-27       http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFCASHFLOWS
         142517 2015-10-27 http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFCHANGESINEQUITY
     
**3** Use the **accessionID** and **extendedLinkRole** to query other elements:

    Task=xbrlChildren
    Element=ProfitLoss
    AccessionID=135173
    GroupURI=http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFEARNINGS
    Linkbase=Calculation

  
    .                                       elementName treeDepth treeSequence order
    .       IncomeLossFromContinuingOperationsInclud...         1            1    21
    .  IncomeLossFromContinuingOperationsBeforeIncom...         2            2    19
    .                                       GrossProfit         3            3    11
    .                                          Revenues         4            4     5
    .                           SalesRevenueServicesNet         5            5     2
    .                              SalesRevenueGoodsNet         5            6     3
    .                          FinancialServicesRevenue         5            7     4
    .                                     CostOfRevenue         4            8    10
    .                                    CostOfServices         5            9     7
    .                                   CostOfGoodsSold         5           10     8
    .                            FinancialServicesCosts         5           11     9
    .                             ExpenseAndOtherIncome         3           12    18
    .            SellingGeneralAndAdministrativeExpense         4           13    13
    .                     ResearchAndDevelopmentExpense         4           14    14
    .    IntellectualPropertyAndCustomDevelopmentIncome         4           15    15
    .                             OtherIncomeAndExpense         4           16    16
    .                                   InterestExpense         4           17    17
    .                           IncomeTaxExpenseBenefit         2           18    20
    .      IncomeLossFromDiscontinuedOperationsNetOfTax         1           19    22

**Comment by campbellpryde** [comment]
The link had an accessionID that did not match the filing.  I have updated the link so if you add your API key this will return the following:

<dataRequest date="2016-02-17T19:07:58-0500">
<fact>
<entity>
<![CDATA[ INTERNATIONAL BUSINESS MACHINES CORP ]]>
</entity>
<accessionID>135173</accessionID>
<filingAccession>0000051143-15-000005</filingAccession>
<filingDate>2015-07-28</filingDate>
<elementName>RevenuesAbstract</elementName>
<namespace>http://fasb.org/us-gaap/2014-01-31</namespace>
<treeDepth>1</treeDepth>
<treeSequence>1</treeSequence>
<order>1</order>
<calculationWeight/>
<calculationEffectiveWeight/>
<leafNode>1</leafNode>
<networkName>
000010 - Statement - CONSOLIDATED STATEMENT OF EARNINGS
</networkName>
<preferredLabel>http://www.xbrl.org/2003/role/terseLabel</preferredLabel>
<networkID>20196574</networkID>
<networkType>presentationLink</networkType>
<networkLink>parent-child</networkLink>
<groupURI>
http://www.ibm.com/role/StatementCONSOLIDATEDSTATEMENTOFEARNINGS
</groupURI>
</fact>....
