### ISSUE TITLE
Can xbrlCIKLookup be used for multiple tickers in one URL? - if yes how?

### ISSUE THREAD

**Issue by gleitold** [xbrlus/data_analysis_toolkit#6]
http://csuite.xbrl.us/php/dispatch.php?Task=xbrlCIKLookup&Ticker=IBM

**Comment by campbellpryde** [comment]
This only allows a single lookup of a CIK.  We pull the data from the SEC
and it only allows one at a time.  We can look into pulling the data from
the XBRL US database to support multiple queries. The API calls the url
below at the SEC then parses out the CIK:

http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=$ticker
&count=0&output=xml

Campbell Pryde

President and CEO

(917) 582-6159


1211 Avenue of the Americas, 19th Floor

New York, NY 10036-8775


*xbrl.us* <http://xbrl.us/> is the national consortium

for xbrl business reporting standards

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate

**Comment by gleitold** [comment]
This only allows a single lookup of a CIK.  We pull the data from the SEC
and it only allows one at a time.  We can look into pulling the data from
the XBRL US database to support multiple queries. The API calls the url
below at the SEC then parses out the CIK:

http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=$ticker
&count=0&output=xml

Campbell Pryde

President and CEO

(917) 582-6159


1211 Avenue of the Americas, 19th Floor

New York, NY 10036-8775


*xbrl.us* <http://xbrl.us/> is the national consortium

for xbrl business reporting standards

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate
